language: php

php:
  # Both 5.6 and 7.0 pull in and older omnipay/common v3.0-alpha.1
  # with an incompatible intergace.
  # PHP 7.1 is now the minimum supported version.
  #- 5.6
  #- 7.0
  - 7.1
  - 7.2

before_script:
  - composer install -n --dev --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - vendor/bin/phpunit --coverage-text
